name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # --- Icônes ---
  cupertino_icons: ^1.0.8

  # --- Carte & GPS ---
  flutter_map: ^6.0.0      # Version stable standard (vérifiez si vous voulez la v8, mais la v6 est plus sûre pour ce code)
  latlong2: ^0.9.1
  geolocator: ^10.1.0      # On garde la version compatible standard
  
  # --- Réseau ---
  http: ^1.1.0

  # --- Caméra & IA ---
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # ✅ VOS ASSETS (IMAGES)
  assets:
    - assets/images/
